#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.8.3 on Thu Nov 15 14:35:52 2018
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((567, 388))
        
        # Menu Bar
        self.MismatchCalcApp_menubar = wx.MenuBar()
        self.object_1 = wx.Menu()
        self.MismatchCalcApp_menubar.object_2 = self.object_1.Append(wx.ID_ANY, "Quit", "")
        self.Bind(wx.EVT_MENU, self.doQuit, id=self.MismatchCalcApp_menubar.object_2.GetId())
        self.MismatchCalcApp_menubar.Append(self.object_1, "File")
        self.object_3 = wx.Menu()
        self.MismatchCalcApp_menubar.object_4 = self.object_3.Append(wx.ID_ANY, "About", "")
        self.Bind(wx.EVT_MENU, self.doAbout, id=self.MismatchCalcApp_menubar.object_4.GetId())
        self.MismatchCalcApp_menubar.Append(self.object_3, "Help")
        self.SetMenuBar(self.MismatchCalcApp_menubar)
        # Menu Bar end
        self.vswr1Text = wx.TextCtrl(self, wx.ID_ANY, "")
        self.rl1Text = wx.TextCtrl(self, wx.ID_ANY, "")
        self.Z1Text = wx.TextCtrl(self, wx.ID_ANY, "")
        self.vswr2Text = wx.TextCtrl(self, wx.ID_ANY, "")
        self.rl2Text = wx.TextCtrl(self, wx.ID_ANY, "")
        self.Z2Text = wx.TextCtrl(self, wx.ID_ANY, "")
        self.mmAmplText = wx.TextCtrl(self, wx.ID_ANY, "")
        self.mmPhaseText = wx.TextCtrl(self, wx.ID_ANY, "")
        self.Z0Text = wx.TextCtrl(self, wx.ID_ANY, "50")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_TEXT_ENTER, self.vswr1Entered, self.vswr1Text)
        self.Bind(wx.EVT_TEXT_ENTER, self.rl1Entered, self.rl1Text)
        self.Bind(wx.EVT_TEXT_ENTER, self.Z1Entered, self.Z1Text)
        self.Bind(wx.EVT_TEXT_ENTER, self.vswr2Entered, self.vswr2Text)
        self.Bind(wx.EVT_TEXT_ENTER, self.rl2Entered, self.rl2Text)
        self.Bind(wx.EVT_TEXT_ENTER, self.Z2Entered, self.Z2Text)
        self.Bind(wx.EVT_TEXT_ENTER, self.Z0Entered, self.Z0Text)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("frame")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        object_5 = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)
        label_1 = wx.StaticText(self, wx.ID_ANY, "vswr")
        sizer_1.Add(label_1, 0, wx.ALIGN_CENTER | wx.ALL, 5)
        sizer_1.Add(self.vswr1Text, 0, wx.ALIGN_CENTER | wx.ALL, 5)
        label_3 = wx.StaticText(self, wx.ID_ANY, "r.l.")
        sizer_1.Add(label_3, 0, wx.ALIGN_CENTER | wx.ALL, 5)
        sizer_1.Add(self.rl1Text, 0, wx.ALIGN_CENTER | wx.ALL, 5)
        label_4 = wx.StaticText(self, wx.ID_ANY, "Z")
        sizer_1.Add(label_4, 0, wx.ALIGN_CENTER | wx.ALL, 5)
        sizer_1.Add(self.Z1Text, 0, wx.ALIGN_CENTER | wx.ALL, 6)
        object_5.Add(sizer_1, 1, wx.EXPAND, 0)
        label_5 = wx.StaticText(self, wx.ID_ANY, "vswr")
        sizer_2.Add(label_5, 0, wx.ALIGN_CENTER | wx.ALL, 5)
        sizer_2.Add(self.vswr2Text, 0, wx.ALIGN_CENTER | wx.ALL, 5)
        label_6 = wx.StaticText(self, wx.ID_ANY, "r.l.")
        sizer_2.Add(label_6, 0, wx.ALIGN_CENTER | wx.ALL, 5)
        sizer_2.Add(self.rl2Text, 0, wx.ALIGN_CENTER | wx.ALL, 5)
        label_7 = wx.StaticText(self, wx.ID_ANY, "Z")
        sizer_2.Add(label_7, 0, wx.ALIGN_CENTER | wx.ALL, 5)
        sizer_2.Add(self.Z2Text, 0, wx.ALIGN_CENTER | wx.ALL, 5)
        object_5.Add(sizer_2, 1, wx.EXPAND, 0)
        label_8 = wx.StaticText(self, wx.ID_ANY, "mm Error Limits (dB):")
        sizer_3.Add(label_8, 0, wx.ALIGN_CENTER, 0)
        sizer_3.Add(self.mmAmplText, 0, wx.ALIGN_CENTER, 0)
        static_line_1 = wx.StaticLine(self, wx.ID_ANY)
        sizer_3.Add(static_line_1, 0, 0, 0)
        label_9 = wx.StaticText(self, wx.ID_ANY, "max Phase error +/-:")
        sizer_3.Add(label_9, 0, wx.ALIGN_CENTER, 0)
        sizer_3.Add(self.mmPhaseText, 0, wx.ALIGN_CENTER, 0)
        object_5.Add(sizer_3, 1, wx.EXPAND, 0)
        label_10 = wx.StaticText(self, wx.ID_ANY, "Zo:", style=wx.ALIGN_CENTER)
        sizer_4.Add(label_10, 0, wx.ALIGN_CENTER, 0)
        sizer_4.Add(self.Z0Text, 0, wx.ALIGN_CENTER, 0)
        object_5.Add(sizer_4, 1, wx.EXPAND, 0)
        self.SetSizer(object_5)
        self.Layout()
        # end wxGlade

    def doQuit(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'doQuit' not implemented!")
        event.Skip()

    def doAbout(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'doAbout' not implemented!")
        event.Skip()

    def vswr1Entered(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'vswr1Entered' not implemented!")
        event.Skip()

    def rl1Entered(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'rl1Entered' not implemented!")
        event.Skip()

    def Z1Entered(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'Z1Entered' not implemented!")
        event.Skip()

    def vswr2Entered(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'vswr2Entered' not implemented!")
        event.Skip()

    def rl2Entered(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'rl2Entered' not implemented!")
        event.Skip()

    def Z2Entered(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'Z2Entered' not implemented!")
        event.Skip()

    def Z0Entered(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'Z0Entered' not implemented!")
        event.Skip()

# end of class MyFrame

class MyPanel(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyPanel.__init__
        kwds["style"] = kwds.get("style", 0) | wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyPanel.__set_properties
        pass
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyPanel.__do_layout
        object_6 = wx.BoxSizer(wx.VERTICAL)
        label_2 = wx.StaticText(self, wx.ID_ANY, "label_2")
        object_6.Add(label_2, 0, 0, 0)
        self.SetSizer(object_6)
        object_6.Fit(self)
        self.Layout()
        # end wxGlade

# end of class MyPanel

class mmCalc(wx.App):
    def OnInit(self):
        self.MismatchCalcApp = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.MismatchCalcApp)
        self.MismatchCalcApp.Show()
        return True

# end of class mmCalc
